title = "duing.dev"
baseURL = "duing.dev"
languageCode = "en-us"
theme = "Blonde"

pygmentsUseClasses = true
assetDir = "static"

[outputs]
  section = ["HTML", "ATOM"]

[permalinks]
  blog = '/blog/:year/:slug/'

[author]
  name = "Eduardo Lemos Rocha"

[mediaTypes."application/atom+xml"]
  suffixes = ["xml"]

[outputFormats.Atom]
  name = "Atom"
  mediaType = "application/atom+xml"
  baseName = "atom"

[outputFormats.RSS]
  mediaType = "application/rss+xml"
  baseName = "rss"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true
