#+hugo_base_dir: ../
#+hugo_tags: lesson recommendation

#+title: Beyond Hackers

#+date: 2023-07-09
#+author: Eduardo Lemos

The Cathedral and the Bazaar by Eric S. Raymond is a perfect union of philosophy, economics,
and software development culture. The reverberations of his theory are fascinating and explain
much more than just why you should care about open-source software.

Needless to say that I highly recommend the reading, there are aspects that he identified within
the Hacker Culture that explain more than meets the naked eye. I'm here to suggest a few possible
explanations for such observations and how the connection between those aspects and a hacker is more than
just making money via coding.

* Context

In one of the appendixes of the book, Eric describes in more detail a guide on how to become a hacker yourself.
One of the most important points is that the selfish reason to become a hacker, in order to be accepted in the tribe,
is already a sign that you are not one; only when a known member calls you a Hacker that you become one.
Participating in this decentralized justice league is a consequence of possessing a specific set of actions
and mindset more than anything else.

The Hacker philosophy is about exploring a diverse set of problems with extensive enthusiasm. A Hacker needs to get his mind
straight to the point that distractions, e.g., sex, money, and social approval, will not affect his direction toward the goal.
Fun throughout this process is more than mandatory; boredom is treated like your worst enemy. Appreciation of competence, other hackers' time, and
freedom are paramount values to you. In regards to others, what do you care? Your reputation among them.
The tribe respects the ones that push the /gift culture/ forward not because they thrive for the gains and fame, but because they see
value on it *beyond* such futile and material gains.

Later on, Eric lists what he called "Points for Style", aspects that many members of the tribe own:
- Learn to write your native language well.
- Read science fiction and go to science fiction conventions.
- Study Zen and/or take up martial arts
- Develop an analytical ear for music. Learn to appreciate peculiar kinds of music. Learn to play some
  musical instrument well, or how to sing.
- Develop your appreciation of puns and wordplay.

I have a few thoughts on why those points seem to be frequent.

* Communication

The first point that my friend Edil brought me once is the fact that all of those activities involve communication
of some sort. The ability to communicate in a myriad of different means stress the overall capability of communicating well
and in an effective manner.

Hackers are builders by nature. They see joy in building solutions for intricate problems. How can they pass this knowledge ahead
if they can't communicate properly? Does it matter that your epiphany solves the problem if it will die with you? How dare you waste others'
time and brainpower solving the same solution that you already crossed from the list?

You can only hone your explanations if you dominate the natural language that you will pass torches further. Maybe exploring languages' intricacies,
such as metaphors, metonymies, puns, and wordplays, can help you pass the message through, so reading fiction will arm you with such tooling. What about non-verbal
communication? Martial arts and general arts fulfill this duty perfectly. Master all of them to be fully confident that your knowledge will be able to spread
across the tribe. Your legacy and contributions will be secured. The art of the Hacker is to make problems extinct, i.e., it will remain solved even after you
pass away.

* Creation

In modern times, we are used more to the verb "consuming" rather than "creating". We spend more time in a passive state of mind, absorbing all sorts of entertainment,
social media, and advertisements. This out-in process makes our creative counterpart go numb. We purposely allow the best set of skills to get less used because
we are spending a lot more time in the inertia of doing nothing. Hackers must exercise the in-out process much more. Maybe it is fair to say that the modern culture
is completely the opposite of what the Hacker Culture preaches and defends.

Because fun is within solving problems, and a hacker wants to contribute to his culture, creative activities must be the law. All the aspects listed above have this to some
degree. You can create great academic material if you dominate natural language. You can create a solid avenue to make people understand hard concepts and values with
an interesting and passionate piece of fiction. You can create an outstanding spectacle with a disciplined demonstration of martial arts. You can create a beautiful
picture that will be worthy of extensive contemplation from your peers because of how well it portrays a message. You can create music that will touch the most sensitive parts
of human nature, showing emotion as a core value.

My friend Breno said it well once: "Don't consume, create!"

* Conclusion

It seems to me that communication and creation are so fundamental to the nature of a hacker that the aforementioned activities just reflect this inner instinct.
You feel the need to practice as much as you can the art of creating and being able to pass your creation to the future generation. You do that not because you
wish fame or buff your ego, but because there seems to be value in doing so.

Not everything is rosy though. When we reach the point in which software creation stop being fun then we must fear for our future. If the heroes of creation stop
doing their endeavors because the fun ceased, this is when the beginning of the end will start. A symptom of this dystopia is when the tribe is losing members and the
culture is slowly going to oblivion. We can't allow such a horrendous fate to happen.
 
