#+hugo_base_dir: ../
#+hugo_tags: lesson

#+title: My Crime against Writing

#+date: 2026-04-05
#+author: Eduardo Lemos

I want to confess a crime I committed during my youth.

A crime so despicable words can hardly begin to describe
its weight. Only in recent years has the resulting shame started to burn my
mind as my deserved punishment. Its scars are now engraved in me,
and forever I will be reminded of my sin.

I'm here before you to seek atonement and forgiveness.
The nature of the crime? Misjudgment and terrible characterization of
the act of /writing/.

* School

Ever since my days of high school, I have always felt like there was
something fundamentally rotten about writing. And with this, I mean the /act/ of
writing. Putting words in a sheet of paper to be read later.

Now, with the gift of retrospect, I can understand the reason for that judgment.
Somehow, my old self was capable to identifying something murky and ghastly in the
/justification/ they gave me to write. Back then, it was not because writing
is a practice, in fact /the/ practice, dedicated to reifying our thoughts. Even worse,
it was not even about writing being one exercise of /language/, one of the
most important, if not the most important, activities in developing any
sort of knowledge. They told me it was because writing is a way to evaluate my exercise
of /critical thinking/, whatever that is supposed to mean.

So, some high school courses, such as literature, history, geography, etc, used
writing as a way for you to extensively answer questions in a test.
At first glance, there is nothing to worry about. It is completely reasonable that
particular topics require some detailed justification when asking a serious question.
The problem starts in the /form/ in which the written answer takes, and the
dedicated training students must go through to achieve such form.

/This/ training is the beginning of the end. A child and/or young adult cannot judge
whether it makes sense to create answers in this fashion, especially given that the evaluators
are telling them this is the pinnacle of writing. Not satisfied, they possess a very
strong utilitarian argument up their sleeve: after school, the evaluation you must
undertake to join college will /also/ use this form to assess you. You'd better master it!
John Stuart Mill would be very happy to know that, being the country that it is, Brazil's
citizens cannot ignore utilitarian arguments like this one. There are entire economic and
social realities that can only sustain themselves if this system works, which is indeed
still the case.

Hence, even if you /were/ the weirdo child who sits alone at the turning of the staircase
each day, reading, there is no escape for you. It does not matter /at all/ which authors
you read or understand to be better in arguing about some topic; you will be forever
locked into a particular form of prose. Educators will say it is /the/ form, mind you.

And you feel mostly alone in this. Your colleagues either don't care about what is going on,
or they fall into two separate scenarios. First, they may understand this is all
a circus, but their utilitarian side cannot dismiss it. They have to make their parents proud
after all; and joining a public university is one path to accomplish that. Or second,
and worse, they /actually believe/ that if you follow these rules,
your destiny is to be a good writer exercising your "critical thinking". This latter result
does not startle anybody who already understands that rule-following is one of the preferred
strategies for pretty much everything nowadays. If we /believe/ that we can follow rules like
a checklist to be /moral/ or /good/ in modern times, you cannot tell me you
don't believe they are doing the same for writing.

* Form

This particular form of writing is easily identifiable. As an evaluation instrument, both
for schools and to join college, there are constraints on the form that must be followed.
You gotta remember: someone with a deadline will have to read one of these for /each/ student.
This requirement forces some sort of predictability on the form. Hence, the text is usually
between 4 and 5 paragraphs. The principle goes deeper: each paragraph also brings some
expectations to its content. And this is where the real mess starts.

Some paragraphs, particularly the second to fourth, are said to better accommodate specific
"kinds" of ""arguments"" (more on this later). Yes. We are taught that instead of some
logical or flow/pacing coherence, there should be priority on /where/ something is being
written; which /position/ it is placed in comparison to the whole.

This classification can also be applied /within/ the paragraph itself. You train yourself to
make the fifth paragraph the conclusion of whatever you are talking about (again, more on this
later), but it does not stop there. There are "kinds" of conclusions you can choose from.
When posed with this dilemma, a dumb mind strives to /comprenhend/ whatever is written in
the course's booklet, i.e., you ask yourself: "what does the recipe book say about this case?
Is there anything in the previous paragraphs that matches a particular kind of conclusion here?
I wrote my previous 2 texts using conclusion of type A, maybe I should do B instead just to
exercise". A mind seeking real /understanding/ becomes not only furious with this recipe
treatment on the practice of writing, but also less motivated to do better.

The cherry on top is the pseudo-recommendations (they are, in fact, mandatory) on the text itself.
Which sentences should you use when writing? What kind of vocabulary should be employed? Do not
worry, fellow student, the potentates of the government will pass the right choices down the
chain to your local teachers. Eventually, you notice that there is some serious circumlocution
going on, i.e., you are taught to have some strong desire to be more indirect and to use
more words than necessary. And don't fool yourself: it is doing harm to the prose's clarity.
And you know it.

The connivance is sometimes palpable in everybody, including the teacher.
Everyone around you makes jokes about what you /actually mean/ in your text, and somehow
there is an immense distance between what is spoken and what is being written. Of course,
for writing, being the actual practice of making thoughts tangible, this outcome should be
somewhat expected. However, you can't help but notice the gap getting larger as you
learn more bureaucratic
and unnecessary words to achieve the perfect form that the adults are expecting from you.

But, inside the very few students' enlightened minds, some tension starts to
build up. They keep telling themselves the same things over and over again:
"man, this sure is a lot of words to say so little! What a bunch of indirect ways to say
something so damn simple! Who talks in this way? Why must writing be this miserable? Is /this/
what waits for me at university?".

At the time I was asking these questions, I also stumbled upon the fact that such rules for
writing were being combined with "/What/ should I say in my writing?". You do not have to be
a genius to notice that the educational system being what it is, they have a lot of influence
on what is being taught in schools content-wise. Hence, it is not a surprise that their control
extends beyond just /how/ a student may write something, but also /what/ is being written, i.e.,
what kind of ""arguments"" should be favored. If you filter which questions should be asked /and/
the standards of the answers to those questions, you are a glimpse away from being able to create
any narrative, including political ones. You can foresee the potential disaster of this
miles away.

At the end of high school, I was very disappointed and furious with both answers to these
situations -- /what/ I should write about and /how/ I should write it -- that I convinced
myself that, and this is my confession, /writing itself/ is miserable.

* College

My college days did not improve my situation, although they did not make it that much worse either.
The damage caused by the worm in my brain, implanted during high school, did not grow. But it
did stay there.

Most of the writing during my bachelor's was nothing worthwhile. I wrote reports of what happened
during experimental courses. I wrote simple slide decks sometimes. Rarely was prose necessary
to answer something. I did have to read some /papers/ either engineering-related or
computer-science-related. At the time, I didn't pay much attention to them.

During extracurricular projects, something changed. As I read more papers,
necessary to gather enough context for the project, I started to notice how diverse
they were structure-wise in comparison to what my writing-farm recipe school has taught me.
More often than not, the form of the paper could not save it from it being boring (to me at the
time, at least), but it started to crack /some/ of these notions consolidated in my brain.
No matter how diverse the papers could be, misery would always wait for me at the end of the
tunnel when it came to writing.

Cracks in this mental dam spread when I did my graduation project. My mentor at the time
convinced me that writing and reading being boring were symptoms of something much greater
in the academic space, but this can be the subject of another post. What matters for this one
is that the nightmare was finally over for me; writing stopped being a complete waste of my time.

* Learning

This revelation of writing not being useless as a practice came to me with an increase in the
practice of reading. Richard Mitchell once said that the point of reading
is /understanding/, but I think this is still incomplete when taken in isolation.
You need to take into account one of his other lessons: that writing is /the/
way to make concrete /your/ understanding.

When reading, we are absorbing other persons' understanding, but this is not immediately
/sewed/ to /our/ current web of knowledge. Our intuition misguides us to think that knowledge's
construction is done by layering bricks, almost like these pieces are all commensurable, i.e.,
you treat each layer as equal to every other one and gluing them together is simply additive.
The expectation should be a tangled mess, thus resulting in false analogies and incorrect inferences.

Fortunately, that is not how /learning/ works. This myriad of ideas and their respective
understanding live in the mind encoded in the form of /language/. When common parts
start to appear between those pieces, we are prompted to finally sew those loosely tied
parts, again using language. In the act of doing so, we
may do a bad job, and inaccuracies can be introduced, and thus errors will follow.
This is especially the case when trying to accomplish this either via speaking or reading.
This is one of the reasons we are much more forgiving when /speaking/ to others
and they make mistakes, we fill the gaps of what they /might have meant/ instead of what they
/said/, given that speaking has non-verbal communication and intonation available to compensate for
these imperfections. However, this leads us to a problem: everything is too foggy, and we lack the proper
instruments to crystallize what our intuition is pointing at when it comes to our /own/
understanding. 
/Writing/ is /the/ practice which, when done with excellence, leads to the least
amount of errors when doing this endeavor, because it uses /language/ to bring forth both
intelligibility /and/ precision to the practice. If you are unintelligible or imprecise during your writing,
how can you understand what you /meant/ when you /wrote/ it? This is why its standards of excellence
/requires/ you to have mastery of the language in which the piece is being written in.

Using Alasdair's definition of an internal good
of a practice -- an abstract profit that can only be acquired by the execution of the practice
and the pursuit of its excellence -- one could say that the internal good of writing is
/our own understanding/. Just like if some understanding cannot be /put into language/ it cannot
/exist/, if you cannot /write/ what you think you understand, you just do /not/ understand it.
And it is important to note that the opposite /is/ possible; you /can/ write things that you don't
understand /yourself/. Such regurgitation, when it happens, will beg the question: "how does a mind that write like
/that/ actually /work/?". Thus, it is either the case that a mind that babbles written nonsense is
suffering from insanity and/or incompleteness, or there are second intentions behind such prose. Mitchell does an
excellent job exploring these two hypotheses, so, instead of daring to do a better job, I will
just recommend his pieces.

* Conclusion

The complete ignorance of this line of thought makes me ashamed. I was too naive and gullible
to ever have believed in that lifeless, soulless, utilitarian, and biased prose. Ever since this has
been introduced to me, my inscrutable pieces during high school are a reason for embarrassment.
Even though I do not practice that previous hokum, it does not change the fact that I once
condemned one of the most important practices with regard to being a human; the one that enables
my own understanding. Perhaps it is not
too late for redemption, but it is undeniable that I have to accept my late arrivals to some
studies as the cost of this crime. I will probably always be behind in the intellectualism
that I crave.









